language: python

os: linux

services:
  - docker

before_install:
  - if [[ "$RUN_DOCKER" == "yes" ]]; then docker pull iotjs/js_remote_test:0.6; fi

install:
  - pip2 install pylint

script: "tools/travis_script.py $OPTS"

env:
  matrix:
    - OPTS="--check-pylint"
